### ISSUE TITLE
audit our mailserver deliverability

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#799]
Related resources:
- [x] https://support.google.com/mail/answer/6227174
- [x] https://support.google.com/mail/answer/81126
- [x] http://www.dkim.org/
- [x] https://support.google.com/a/answer/33786
- [x] https://dmarc.org/
- [x] https://support.google.com/a/answer/168383
- [x] https://support.google.com/mail/answer/6330403
- [x] https://transparencyreport.google.com/safer-email/overview
- [ ] https://www.mail-tester.com/
- [ ] https://glockapps.com/

**Comment by w1stler** [comment]
@Rafalkufel do you want to tackle this one?
